### ISSUE TITLE
[Suggestion] Extension download workaround for README

### ISSUE THREAD

**Issue by NoozAbooz** [NeverDecaf/discord-PWA#12]
Hello,
As you may know, when you download the extension, it says its not from the Extension store and gets deleted by chrome. I found that if you right-click the download link and save it as a link, chrome doesn't remove it and you can even upload it to chrome with dev mode on. I suggest this be added to README.

**Comment by ghost** [comment]
This behavior is handled by the chrome flag `#extension-mime-request-handling`. The flag's default value is `Always prompt for installation`. There are a number of ways to get around the problem.

You can change this flag to `Download as regular file`, then visit the link in Chromium.
You can visit the link in another browser such as Firefox, which downloads the extension as a regular file by default.
I haven't tried your suggestion, but perhaps it's viable for Chrome users.

I was under the impression that it wasn't possible anymore to install third-party extensions to Chrome (the mainstream one, not Chromium or Ungoogled Chromium, which I know it works on) due to security restrictions. Are you saying you were able to get it working on Chrome, or Chromium? If it's Chrome, this is news to me.

**Comment by NeverDecaf** [comment]
IIRC `#extension-mime-request-handling` is a flag added by ungoogled-chromium and isn't available in vanilla Chrome/Chromium.

**Comment by NoozAbooz** [comment]
For me, I was using the chromium which came default with rpi os
