### ISSUE TITLE
[Question] What about the Electron?

### ISSUE THREAD

**Issue by SpacingBat3** [NeverDecaf/discord-PWA#15]
# Hi there,

Just to mention at first, this is not an issue, but rather a question. And I don't expect it will be treated as the important one.

As you might know me earlier from the issue #6, I've also started to search for the alternative to the chrome web applications – at first I've found this repository, but the way it looked and worked weren't just as great as I expected and I knew i need to look for something different. Then, I've found the [nativefier](https://github.com/jiahaog/nativefier) that uses the [electron](https://www.electronjs.org) engine to generate the app. This sollution were good for having generic web app generation, but it weren't when you want to maintain, add to it code or tweak it. So I've jumped then to the electron itself – today I have made [this repository](https://github.com/SpacingBat3/electron-discord-webapp). As today it has many functionalities like a working tray or "single session lock", it still need much more than today.

I'm writting there mostly to give this sollution some attention (not just for bigger insterest with my repository). I'm also curious why you didn't tried by yourself doing the app with the Electron – even the official Discord client is still using it.

## Some advantages of using Electron
- can be themed with CSS,
- can be built on different machines and OS (every device/os that can install Electron): Windows, MacOS and Linux with the support for both X86 and ARM architectures,
- allows customizing most aspects of the app itself – thanks to the advanced Electron API,
- the tray support and running it "with EXE" makes it look more natively to the desktop than any chrome app,
- based on Chromium (so you might expect it will work similar to the web apps you've made),
- as it is still a web app, there app is always in the latest version :smile:

## Disadvantages:
- no support for the ChromeOS nor Android,
- need to install electron to run the app (mostly when building from the source, it is rebranded and copied with its dependencies to the package – so it can be run standalone);
- not integrated with Chrome (both advantage and disadvantage depending on the expected behaviour of our app),
- there's no way to make the "blink taskbar icons" behaviour on Linux and MacOS (but I believe it is not needed if you wish to make the app as much close to the full client as it is possible – Discord doesn't have this feature either).

## Help wanted
As you know much about the CSS, HTML and JS why don't you help me to improve this app? As I'm myself rather the begginer with the JS, CSS and HTML (from JS I know only the basics and the Electron syntax that I've learnt from [their docs](https://www.electronjs.org/docs) – but I've also the experience with writing a shell scripts on Linux), this project would be way better having some collaborators / contributors with good JS and CSS knowledge.

The good example where I need help is making the custom tittle bar – but I don't have a proper assets (images of the buttons) + don't know how to adapt your CSS to it (however it is possible to do with same ways you did it on your web apps and even Electron has in it's API declarations to create a window without borders and to make a part of the HTML site draggable).

**Comment by NeverDecaf** [comment]
Part of the reason I started this project in the first place is *because* the official client uses Electron. I don't want to run a separate browser (with all the resource usage that implies) just to display a single webpage.

The main reason I created the original Chrome app is that I didn't like how the official client was granted access to my computer via native APIs. I realize you can disable this when creating your own Electron app, but I didn't want to burden users with either needing to trust that I haven't added any malicious code to binaries (whether intentionally or by error), or audit and compile the app from source every time there is an update.

As for the title bar, it is all generated through CSS and HTML via the `<svg>` tag, there are no images used. If you are willing to run the official app, you can open the built-in chromium devtools (`ctrl+shift+i`) to see exactly how everything is done. 

I should also mention that this web app (and all PWAs) can be themed with CSS and modified/extended with JS via extensions like TamperMonkey and Stylus. If you are interested in modifying Discord there is something called BetterDiscord(?) with a large community developing themes/extensions for the official client, perhaps you will want to make your app compatible with their themes so users can instantly have access to a large library of customization options.

**Comment by SpacingBat3** [comment]
ok, thank you, gonna close that issue...
