### ISSUE TITLE
Unable to install: 'Invalid value for 'web_accessible_resources[0]'

### ISSUE THREAD

**Issue by ghost** [NeverDecaf/discord-PWA#31]
Hello again. Unfortunately, I believe your latest update to the extension broke it. With the latest update, attempting to install the file Discord-PWA-Bypass.crx brings up the error `Package is invalid. Details: 'Invalid value for 'web_accessible_resources[0]'.'.`. The other crx file in the repository dated 5-20-2021 installs correctly, but it continues to prompt for an update.

While I have this opportunity I would like to thank you for your work. I recommend it to people all the time, and they've started recommending it to others. I hope you know that many people appreciate it even if they are not vocal about it in ways that you can see. Most of all I hope that you do this because you enjoy it. If that is the case, I encourage you to keep it up!

**Comment by NeverDecaf** [comment]
Firstly, thanks for the kind words! It's nice to hear this is appreciated, but of course I'm doing this because I enjoy (and use) it myself.

As for the error, this is most likely because your browser doesn't support [manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/), which 1.4.5 uses. I specifically made that other file to be the last backup of the manifest v2 version which explains why it's working. Can you post your browser and version just to be sure this is actually the issue?

I wasn't sure if any users would be affected by the switch, but if this really is the issue I might need to reconsider how to handle the migration to manifest v3, most likely I will create a separate branch that doesn't get feature updates (as they will only work on manifest v3) and have manifest v2 versions of the extension update to that branch. Of course I can't guarantee it will always be working as I'll be continuing development exclusively on the manifest v3 version as google plans to drop support for manifest v2 in the near future.

**Comment by ghost** [comment]
I was making a big mistake! Thank you, I have fixed it and I don't believe it should be a common issue.

As a result of testing different updaters, I have had more than one installation of ungoogled-chromium. So, depending on the way I was opening the application, it would either open the latest version or a version from September 2020. Unlike Firefox, if Chromium was already open then new tabs of the same profile would open without issue on whichever version was already open. I had no indication this was happening until now.

I have cleaned that up, reinstalled the browser, and imported my User Data. I'm no longer having any issues installing or using the extension. If it happens to anyone else, that's why I named the issue the way that I did.

For most users, there should be no concerns about upgrading, especially if they use the ungoogled version of the browser. The only practical situation that I can imagine where a manifest v2 version would be needed is when users do not have software installation rights over their machines, like employees and students, forcing them to use an older version of Chrome.

**Comment by NeverDecaf** [comment]
Nice, good thing you found that other issue through this, could have been a disaster in the making.

As for users needing manifest v2, all I can really think of is maybe there is a fork out there that intentionally won't support v3; this is pretty unlikely but just in case I've added `Discord-PWA-Bypass-mv2.crx` which you can use if you are in a situation where you cannot install manifest v3 extensions. **This version of the extension will not receive feature updates and may randomly break in the future, do not use it unless you absolutely must.**
