### ISSUE TITLE
Allow compatibility with BetterDiscord X 

### ISSUE THREAD

**Issue by jafuuu** [NeverDecaf/discord-PWA#41]
For people who wants to use extensions in the PWA

https://github.com/Strencher/BdBrowser

**Comment by ddodogames** [comment]
hey @jafuuu i would like to inform you that most of the extensions claiming to be a browser version of betterdiscord client are mostly a scam and are only designed to grab discord user accounts token, for my personal experience:

in late 2021: there was a similar extension to the original project (BDbrowser) and it was existing on google chrome addons store, however after using tools to download the extension to check it's source code it contained some weird files that are mostly used to grab people's token, after i have contacted the original developer of bdbrowser he has said that the google chrome addon version was mostly stolen from his original project and are modified to grab discord account tokens, that's why the original developer had to update bdbrowser to add a warning to warn people that they should not download any extension  claiming to be betterdiscord extension than the original github project (https://github.com/Strencher/BdBrowser)


i also found out the responsible user of the malicious extension and decided to warn people about it, hope you understand that, i am only here to warn you nor wanting to start a drama or argument with you, you shouldn't trust any sus extensions on google chrome webstore nor shady projects that are closed source and coming from a unknown source

**Comment by ddodogames** [comment]
and to be clear, the only legit extension that allows you to run betterdiscord in the web client of discord is the one made by [Strencher](https://github.com/Strencher/BdBrowser)

**Comment by jafuuu** [comment]
I changed the original comment to not include de Chrome Extension link, I knew about the existence of Strencher's extension.

Still you need to disable the PWA container in order to make Strencher extension work, any work around?

**Comment by NeverDecaf** [comment]
> Still you need to disable the PWA container in order to make Strencher extension work, any work around?

Edit the `manifest.json` from the BdBrowser extension to include the "all_frames" option like so:
```   
"content_scripts": [
        {
            "matches": ["https://*.discord.com/*"],
            "js": ["./dist/backend.js"],
            "all_frames": true
        }
    ],
```

**Comment by toprak** [comment]
your workaround gives me error @NeverDecaf
