### ISSUE TITLE
Package is invalid (CRX_REQUIRED_PROFF_MISSING)

### ISSUE THREAD

**Issue by SpacingBat3** [NeverDecaf/discord-PWA#6]
When trying to download crx extension, I get an popup:
_Package is invalid (CRX_REQUIRED_PROFF_MISSING)_

I tried to install it on chromium ARM64 version 84.0.4147.89 on the Raspberry Pi 4B running Manjaro ARM.

**Comment by ghost** [comment]
Hi, I noticed this too when I was trying to recommend this project to someone else. This seems to be a Chromium bug which occurs on any Chromium-based browser on any OS, even mainstream Chrome. I may be wrong but I think it happens because the extension isn't listed in the Chrome Web Store and there are some checks somewhere to prevent it from loading.

If you try downloading the extension with another browser (to avoid it trying to install instantly) and drag it on to the chrome://extensions page, you might get a warning that says it's not from the Chrome Web Store and as such has been disabled. In mainstream Chrome, you can't enable extensions that aren't from the Chrome Web Store. So this extension literally isn't compatible with mainstream Chrome. I recommend Ungoogled Chromium instead of Chromium, and luckily the creator of this project creates an updater and a Web Store enabler for it. I suggest using the updater to install the browser.

**To install this extension, unfortunately you must currently download it with another browser, extract the file's contents to a folder (it's basically a renamed zip. I use 7-Zip for this) and at the top of chrome://extensions/, "Load Unpacked" the folder containing the extension contents.**

Don't forget to also make the flag changes for the PWA so you can see badges in the program's icon.

**Comment by SpacingBat3** [comment]
Ok, I was even able to download it with chromium by pasting this url: https://raw.githubusercontent.com/NeverDecaf/discord-PWA/master/Discord-PWA-Bypass.crx in my adress bar (even *clicking* on it works).Kinda weird, as it didn't installed automatically as before, but instead it just saved itself in my downloads directory. It's all working now as intended.

Thanks, @daze-2121 for your answer. Closing this issue...
